language: python
python:
    - "3.6"
install: 
    - pip3 install cryptography==2.4.2
    - pip3 install "idna<2.8,>=2.5"
    - python3 setup.py install
    - python3 setup.py install_scripts
script:
    - post-media --help
